[package]
name = "sntk_core"
version = "0.0.1"
edition = "2021"
authors = ["ky0422 (Kim Jun Young)"]
description = "Core library for Sanetaka (sntk) programming language"
license = "MIT"
repository = "https://github.com/ky0422/sanetaka"
