[package]
name = "parser"
version = "0.0.12"
edition = "2021"
authors = ["ky0422 (Kim Jun Young)"]
description = "Core library for Signature programming language"
license = "MIT"
repository = "https://github.com/siglang/signature"

[dependencies]
